<?php
/**
 * @file
 * University of Iowa branding.
 *
 * Adds the University of Iowa branding bar and footer to each page and
 * implements the Google Custom Search.
 */


/**
 * Implements hook_permission().
 */
function uiowa_bar_permission() {
  return array(
    'administer uiowa bar' => array(
      'title' => t('Administer UIowa branding bar'),
      'description' => t('Perform administration tasks for the UIowa branding bar.'),
    ),
    'access uiowa cse results' => array(
      'title' => t('Access Google Custom Search Results'),
      'description' => t('View search results for the Google Custom Search for the University.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function uiowa_bar_menu() {
  $items = array();

  $items['google-search'] = array(
    'title' => variable_get('site_name') . ' Search',
    'page callback' => 'uiowa_bar_build_results',
    'file' => 'includes/uiowa_bar_results.build.inc',
    'access arguments' => array('access uiowa cse results'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/user-interface/uiowa-bar'] = array(
    'title' => 'University of Iowa Branding Bar',
    'description' => 'Configuration for the University of Iowa Branding Bar',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uiowa_bar_config_form'),
    'access arguments' => array('administer uiowa bar'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/uiowa_bar.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_page_build().
 */
function uiowa_bar_page_build(&$page) {
  global $theme_key;

  // Get this module's path.
  $path = drupal_get_path('module', 'uiowa_bar');

  // If the theme being used is the default theme, build the bar.
  // This avoids us building the bar on pages using the admin theme.
  if (variable_get('theme_default', 'none') === $theme_key) {
    $path = drupal_get_path('module', 'uiowa_bar');
    drupal_add_css($path . '/css/uiowa-bar.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    $url = $path . '/js/tag-manager.js';
    $contents = @file_get_contents($url);
    drupal_add_js($contents, array('type' => 'inline', 'group' => JS_LIBRARY * 2));

    module_load_include('inc', 'uiowa_bar', 'includes/uiowa_bar.build');
    
    $uiowa_bar_top_render_array = build_uiowa_bar();

    $page['page_top']['uiowa_bar'] = array(
      '#markup' => render($uiowa_bar_top_render_array),
      '#weight' => 25,
    );
  }
}
