<?php
use Drupal\Core\Render\Element;
/**
 * @file
 * Primary module hooks for Uiowa Bar module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function uiowa_bar_theme() {
    $uiowa_bar_config = \Drupal::config('uiowa_bar.settings');
    return array(
        'uiowa_bar' => [
            'variables' => [
                'config' => $uiowa_bar_config->get('uiowa_bar'),
                'search_form' => NULL
            ],
        ],
        'parts/uiowa_wordmark' => [],
        'parts/uihc_wordmark' => [],
    );
}

/**
 * Implements hook_page_attachments().
 */

function uiowa_bar_page_attachments(&$page){
    $admin_context = \Drupal::service('router.admin_context');
    if (!$admin_context->isAdminRoute()) {
        $page['#attached']['library'][] = 'uiowa_bar/uiowa-bar';
    }
}

/**
 * Implements hook_page_top().
 */
function uiowa_bar_page_top(&$page_top){
    $admin_context = \Drupal::service('router.admin_context');
    if (!$admin_context->isAdminRoute()) {
        $search_form = \Drupal::formBuilder()->getForm('Drupal\uiowa_bar\Form\SearchForm');
        $page_top['uiowa_bar'] = [
            '#theme' => 'uiowa_bar',
            '#search_form' => $search_form,
        ];
    }
}